import operator
from typing import Annotated, Sequence, TypedDict
from langchain_core.messages import BaseMessage
from langgraph.graph import add_messages


class ResearcherState(TypedDict):
    """
    State for the research agent, capturing the conversation history and research metadata throughout the interaction.

    @param researcher_messages: The sequence of messages exchanged between the user and the agent, annotated to be added to the state.
    @param tool_call_iterations: The number of times the agent has called external tools during the interaction, used for tracking and evaluation purposes.
    @param research_topic: The specific research topic identified from the user's input, which guides the agent's research process.
    @param compressed_research: A condensed summary of the research findings generated by the agent
    @param raw_notes: A list of unprocessed notes and findings collected by the agent during the research process, annotated to be added to the state.
    """

    researcher_messages: Annotated[Sequence[BaseMessage], add_messages]
    tool_call_iterations: int
    research_topic: str
    compressed_research: str
    raw_notes: Annotated[list[str], operator.add]


class ResearcherOutputState(TypedDict):
    """
    Output state for the research agent, capturing the final outputs of the research process.
    
    """

    compressed_research: str
    raw_notes: Annotated[list[str], operator.add]
    researcher_messages: Annotated[Sequence[BaseMessage], add_messages]
